### ISSUE TITLE
Wizard command

### ISSUE THREAD

**Issue by fboucquez** [symbol/symbol-bootstrap#103]
Allow params to be filled when running the config command in wizard style.

The plan is to upgrade the default presets with some custom tags:

````
nodes:
    - voting: wizard:boolean:false
      mainPrivateKey: wizard:privateKey:genKey
      transportPrivateKey:  wizard:privateKey:genKey
      harvesterSigningPrivateKey:  wizard:privateKey:genKey
      vrfPrivateKey:  wizard:privateKey:genKey
      votingPrivateKey:  wizard:privateKey:genKey
````

The wizard will ask for those values if --wizard. Otherwise, the default will be generated

Update:
It's a security improvement as the user will not need to write down a custom preset to then encrypt it. Bootstrap will prompt and create the encrypted custom preset on the fly.

I think it will be better to be its own wizard command that generates an encrypted custom preset. The input could probably be a paper wallet. This wizard will be an offline command.
